spring.application.name=PolicyDocumentGenerator

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spirng.jpa.properties.hiberante.format_sql=true

policy.pdf.output-path=
